spring:
  application:
    name: shipping-tracker

server:
  port: 8080

logging:
  level:
    root: INFO
    io.github.tobiashstbrg.shippingtracker: DEBUG
    io.github.tobiashstbrg.shippingtracker.config.RateLimitFilter: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"


  file:
    name: logs/shipping-tracker.log
    max-size: 10MB
    max-history: 7